FROM php:8.3-fpm

RUN apt-get update && apt-get install -y git

WORKDIR /var/www

RUN rm -rf /var/www/html

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

RUN chown -R www-data:www-data .

EXPOSE 9000

CMD ["php-fpm"]