version: "3.3"
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile-back
    container_name: ccca_back
    image: thiagomoraes/ccca
    tty: true
    environment:
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=thiago
      - DB_PASSWORD=root123!@
    volumes:
      - ./back:/var/www
    networks:
      - app-network
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    ports:
      - 8001:80
    volumes:
      - ./back:/var/www
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app    
  db:
    image: mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_USER=thiago
      - MYSQL_PASSWORD= root123!@
    networks:
      - app-network

  # app-front:
  #   build: .
  #   user: 1000:1000
  #   container_name: app_front
  #   ports:
  #     - "3000:5173"
  #   tty: true
  #   volumes:
  #     - ./front:/app/front
  #   networks:
  #     - app-network
  #   entrypoint: "npm run dev -- --host"
  redis:
    image: redis:alpine
    expose:
      - 6379
    networks:
      - app-network
networks:
  app-network:
    driver: bridge